- name: Share sources
  hosts: ansi-node1, ansi-node2
  tasks:
  - name: Add an Apt signing key, uses whichever key is at the URL
    import_tasks: URL_key.yml

  - name: Create a custom MariaDB sources.list file
    import_tasks: mariadb_source.yml

- name: DB server
  hosts: ansi-node2
  vars_files:
  - pkg_vars.yml
  - svc_vars.yml
  - login.yml
  vars_prompt:
  - name: create_databases
    prompt: DB_name
    private: no
  - name: create_user
    prompt: user_name
    private: no
  - name: user_passwd
    prompt: user_pw
    private: yes
    confirm: yes
  tasks:
  - name: Install Packages
    import_tasks: install_pkg.yml

  - name: Start and enable service
    include_tasks: start_svc.yml
    loop: "{{ svc_list }}"

  - name: Open port
    import_tasks: open_port.yml

  - name: Set the root password
    import_tasks: set_root.yml

- name: Remove all anonymous user accounts
    import_tasks: remove_accounts.yml

  - name: Remove the MySQL test database
    import_tasks: remove_db.yml

  - name: Creates database for WOrdpress
    import_tasks: create_db.yml

  - name: Create MySQL user for Guestbook
    import_tasks: create_dbuser.yml
   
  - name: Enable remote login to mysql
    import_tasks: enable_remote.yml

  - name: Restart mariadb
    import_tasks: handler.yml

- name: WEB server
  hosts: ansi-node1
  tasks:
  - apt:
      name: mariadb-client
      update_cache: yes
      state: latest

