- name: install php
  apt:
    name: software-properties-common
    update_cache: yes
    state: latest

- name: ansible_repo
  ansible.builtin.apt_repository:
    repo: ppa:ondrej/php
    update_cache: yes

- name: install lib 
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  loop: ['php8.0', 'php8.0-common', 'php8.0-mysql', 'php8.0-xml', 'php8.0-curl', 'php8.0-gd',  'php8.0-imagick', 'php8.0-cli', 'php8.0-dev', 'php8.0-imap', 'php8.0-mbstring', 'php8.0-opcache', 'php8.0-soap', 'php8.0-zip', 'php-pear' ]



